apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: erichodgins-ca-tls
spec:
  secretName: erichodgins-ca
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: erichodgins.ca
  dnsNames:
    - erichodgins.ca
    - www.erichodgins.ca
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - erichodgins.ca
          - www.erichodgins.ca